# permissions for end users to view azures.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: azure-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: keti-controller
    app.kubernetes.io/part-of: keti-controller
    app.kubernetes.io/managed-by: kustomize
  name: azure-viewer-role
rules:
- apiGroups:
  - auth.hybrid.keti
  resources:
  - azures
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - auth.hybrid.keti
  resources:
  - azures/status
  verbs:
  - get
