# permissions for end users to view kts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kt-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: keti-controller
    app.kubernetes.io/part-of: keti-controller
    app.kubernetes.io/managed-by: kustomize
  name: kt-viewer-role
rules:
- apiGroups:
  - cloud.hybrid.keti
  resources:
  - kts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.hybrid.keti
  resources:
  - kts/status
  verbs:
  - get
