# permissions for end users to view amazons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: amazon-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: keti-controller
    app.kubernetes.io/part-of: keti-controller
    app.kubernetes.io/managed-by: kustomize
  name: amazon-viewer-role
rules:
- apiGroups:
  - cloud.hybrid.keti
  resources:
  - amazons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.hybrid.keti
  resources:
  - amazons/status
  verbs:
  - get
