# permissions for end users to edit watchings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: watching-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: keti-controller
    app.kubernetes.io/part-of: keti-controller
    app.kubernetes.io/managed-by: kustomize
  name: watching-editor-role
rules:
- apiGroups:
  - level.hybrid.keti
  resources:
  - watchings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - level.hybrid.keti
  resources:
  - watchings/status
  verbs:
  - get
