# permissions for end users to view rebalances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: rebalance-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: keti-controller
    app.kubernetes.io/part-of: keti-controller
    app.kubernetes.io/managed-by: kustomize
  name: rebalance-viewer-role
rules:
- apiGroups:
  - level.hybrid.keti
  resources:
  - rebalances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - level.hybrid.keti
  resources:
  - rebalances/status
  verbs:
  - get
