# permissions for end users to view persistentvolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: persistentvolume-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: keti-controller
    app.kubernetes.io/part-of: keti-controller
    app.kubernetes.io/managed-by: kustomize
  name: persistentvolume-viewer-role
rules:
- apiGroups:
  - resource.hybrid.keti
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resource.hybrid.keti
  resources:
  - persistentvolumes/status
  verbs:
  - get
