# permissions for end users to edit persistentvolumeclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: persistentvolumeclaim-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: keti-controller
    app.kubernetes.io/part-of: keti-controller
    app.kubernetes.io/managed-by: kustomize
  name: persistentvolumeclaim-editor-role
rules:
- apiGroups:
  - resource.hybrid.keti
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.hybrid.keti
  resources:
  - persistentvolumeclaims/status
  verbs:
  - get
