# permissions for end users to view warnings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: warning-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: keti-controller
    app.kubernetes.io/part-of: keti-controller
    app.kubernetes.io/managed-by: kustomize
  name: warning-viewer-role
rules:
- apiGroups:
  - level.keti.res
  resources:
  - warnings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - level.keti.res
  resources:
  - warnings/status
  verbs:
  - get
