apiVersion: auth.hybrid.keti/v1
kind: Azure
metadata:
  labels:
    app.kubernetes.io/name: azure
    app.kubernetes.io/instance: azure-sample
    app.kubernetes.io/part-of: keti-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: keti-controller
  name: azure-sample
spec:
  # TODO(user): Add fields here
