apiVersion: resource.hybrid.keti/v1
kind: Node
metadata:
  labels:
    app.kubernetes.io/name: node
    app.kubernetes.io/instance: node-sample
    app.kubernetes.io/part-of: keti-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: keti-controller
  name: node-sample
spec:
  # TODO(user): Add fields here
